### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by dreamer540** [MrTyton/AutomatedFanfic#2]
Hi there,

Could you please provide a brief explanation of what this tool does and how to use it? Specifically, it would be helpful to know:
- By "automated", do you mean that it runs at regular time intervals, or that by running the tool stories will immediately be added/updated in the calibre library?
- Does it require any additional support once run? For example, can I run it and then leave it in the background while I use my laptop?
- What steps do I need to take to integrate this with fanficfare's "get stories from email" function?

Finally, the most recent version of the fanficfare cli that I downloaded using was installed as a .whl, which I'm unfamiliar with. How do I use this tool with that version of fanficfare?

Thanks very much for your help and for building the tool!

ps. I tried to open with python3 on mac to see if there were any help docs/info, and it returned the following error. Not sure if this helps, I'll add it anyway:

```
% python3 fanficdownload.py
Traceback (most recent call last):
  File "fanficdownload.py", line 1, in <module>
    from fanficfare import geturls
ModuleNotFoundError: No module named 'fanficfare'
```

**Comment by MrTyton** [comment]
Hi,

So for the regular time intervals, you'd have to use a scheduling program.
For instance, windows has the "Windows Task Scheduler", linux has Cron. I'm
sure that mac has it as well, but I don't know what it's called.

It doesn't require any additional support once it's run - the scheduling
program will handle everything for you.

There are a few things that you need downloaded - you need fanficfare
installed from the python repository, which you can do with "pip install -u
fanficfare", for instance. Any missing packages will need to be installed
through the same way, which will come from the same error that you posted.
You also need the calibredb installed, which I think happens once calibre
is installed anyways. It also needs to be set up as a webserver.

To integrate with the email, you have to fill out the config_template.ini
with the required fields for everything.

You can use this w/ either fanficdownload.py or with runner_notify.py,
depending on how you want it wrapped.

Does that answer your questions? Sorry that there isn't a step-by-step
guide for this.

**Comment by MrTyton** [comment]
Closing, since now there is a docker file.
