### ISSUE TITLE
How To actually Set Up auto Updates?

### ISSUE THREAD

**Issue by ninjadudexp** [MrTyton/AutomatedFanfic#4]
I am able to get books but still unclear on how to set up auto update or how to set up pushbullet properly. No info on readme

**Comment by ninjadudexp** [comment]
i guess let me elaborate a little more, email downloads are working but its not clear how to update calibre.

**Comment by MrTyton** [comment]
Ok. Over the weekend I will aim to document things better. Sorry for the
delay, IRL has been busy.

**Comment by ninjadudexp** [comment]
No problem, i think the issue is that it keeps renaming folders with different numbers any time a series is added.

Soo book series 1 might randomly be changed to 8 ( might not be random but not sure how to change the way it names folders for it to be consistent so that Calibre has the correct file path at all times)

**Comment by MrTyton** [comment]
Yeah so it needs to use the calibre server to work. I'm working on getting
something with screenshots, I run everything headless so... Yeah

**Comment by ninjadudexp** [comment]
I can switch Calibre to Headless right now it is Headless in a container but has a webui i access

**Comment by ninjadudexp** [comment]
Any update on this

**Comment by MrTyton** [comment]
Updated readme with links and information, sorry for the delay. If the instructions are still unclear, please state.
