### ISSUE TITLE
DB not being written to

### ISSUE THREAD

**Issue by ninjadudexp** [MrTyton/AutomatedFanfic#9]
So i have the Calibre CLI working, it is downloading into the folder and everything, no errors with start up.
Using Calibre generated DB does not seem to get written on, have to hit update library each time.
If i have the script create a folder and DB, calibre says that the DB is corrupted and just reverts back to the original DB.

if i use the content server to try and load the file, it just never gets added always get an error when i have the content server as the location.

**Comment by MrTyton** [comment]
What platform are you running this on? Did you have calibre natively installed and created a library that way, or are you generating the library some other way?

Can you copy/paste the exact errors that you're seeing?

**Comment by ninjadudexp** [comment]
Using docker, there is no error appearing using the default library that
was created on set up. But it's not being written to. If I let your script
build the folder and library file, it comes to as corrupt in calibre itself
when I go to target it as the main library.

**Comment by MrTyton** [comment]
Did you make sure that the calibre server is started up, with the correct username/password, and that you're directing it to the IP address of the computer that it's running on (not 127.0.0.1)?

**Comment by ninjadudexp** [comment]
Yes, i have it on a reverse proxy with its own URL, i can connect to the
server through the web with what i have input in the field without issue.

**Comment by MrTyton** [comment]
The script is just failing silently? What are the logs printing out?

Can you try opening a CLI in the docker terminal and adding something to the calibre library from there, using one of the copied commands from the log output?

If that's not being printed out, then you can copy this line https://github.com/MrTyton/AutomatedFanfic/blob/master/root/app/calibredb_utils.py#L39 and put it before this https://github.com/MrTyton/AutomatedFanfic/blob/master/root/app/calibredb_utils.py#L25 to always log the command output and restart the container. If you don't know how to do that then I can push a new version that has more verbose logging.

**Comment by ninjadudexp** [comment]
No log commands being showed for calibre, could you push a updated version
or a debug version ill push the update right away.

**Comment by MrTyton** [comment]
While I do that, can you please just post the logs that you do have?

**Comment by MrTyton** [comment]
If you give it an hour, then the new version should be live. Run it with an environment variable `-E verbose=true` and it should start printing out more debug information.

**Comment by ninjadudexp** [comment]
2024-07-16 11:31:22 PM - Failed to get URLs: b'[ALERT] Invalid credentials (Failure)'
2024-07-16 11:32:23 PM - Failed to get URLs: b'[ALERT] Invalid credentials (Failure)'
2024-07-16 11:33:06 PM - Failed to get URLs: b'[ALERT] Invalid credentials (Failure)'
2024-07-16 11:34:06 PM - Failed to get URLs: b'[ALERT] Invalid credentials (Failure)'


now i am getting this, nothing is changed. Before it was at least downloading not sure what changed.

**Comment by ninjadudexp** [comment]
sh: 1: Syntax error: end of file unexpected (expecting "then")
sh: 1: Syntax error: end of file unexpected (expecting "then")
sh: 1: Syntax error: end of file unexpected (expecting "then")
sh: 1: Syntax error: end of file unexpected (expecting "then")
sh: 1: Syntax error: end of file unexpected (expecting "then")
sh: 1: Syntax error: end of file unexpected (expecting "then")

**Comment by ninjadudexp** [comment]
```
[calibre]
path="/root/1calibre/config/Calibre Library/"
username=""
password=""
default_ini="/root/1fff/config/defaults.ini"
personal_ini="/root/1fff/config/personal.ini"
```

also not working when the path is the content server

**Comment by MrTyton** [comment]
The failed to get URLs seems to be an email related one, make sure the user/pass is correct or that the token hasn't expired.

Did you set up a username/password on the content server? If not, could you try making those up and adding it to the config? There's a chance that I didn't catch the no user/pass case correctly, so that would help confirm it. 

Also for the environment variable, sorry, I think it needs to be all caps. `-E VERBOSE=true`

**Comment by ninjadudexp** [comment]
```[email]
email = "i@gmail.com"
password = "app password"
server = "imap.gmail.com"
mailbox = "Books"
sleep_time = 60


[pushbullet]
enabled = true
api_key= "API"
device = "DESKTOP"

[calibre]
path="/root/1calibre/config/Calibre Library/"
username=""
password=""
default_ini="/root/1fff/config/defaults.ini"
personal_ini="/root/1fff/config/personal.ini"

```

so prior to your push my settings were like this and it was downloading files,  it just was not writing them to DB now, its not doing either.

![image](https://github.com/user-attachments/assets/7dfe0cb9-4ad3-461e-8808-631625900e81)

**Comment by ninjadudexp** [comment]
in case it helps

![image](https://github.com/user-attachments/assets/833d1ed7-b071-4854-8944-55121a0068c9)

**Comment by MrTyton** [comment]
I didn't change anything about the email gathering at all. There's a chance that the urllib3 update broke that - I can revert that and you can see, though it is odd that that still works on my system. Give it half an hour.

**Comment by MrTyton** [comment]
And once that is pushed, try changing the `path="/root/1calibre/config/Calibre Library/"` to be the URL of the content server, instead of the direct file access.

**Comment by ninjadudexp** [comment]
ok ill try it in 30, but i also went ahead and just use python looks like it is having problems loading up the main() and __init__ function

```  File "C:\Users\c\Documents\AutomatedFanfic-master\root\app\fanficdownload.py", line 185, in <module>
    main()
  File "C:\Users\c\Documents\AutomatedFanfic-master\root\app\fanficdownload.py", line 153, in main
    email_info = url_ingester.EmailInfo(args.config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c\Documents\AutomatedFanfic-master\root\app\url_ingester.py", line 91, in __init__
    config = tomllib.load(file)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 598, in parse_value
    return parse_one_line_basic_str(src, pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 409, in parse_one_line_basic_str
    return parse_basic_str(src, pos, multiline=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 575, in parse_basic_str
    pos, parsed_escape = parse_escapes(src, pos)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 490, in parse_basic_str_escape
    return parse_hex_char(src, pos, 8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tomllib\_parser.py", line 504, in parse_hex_char
    raise suffixed_err(src, pos, "Invalid hex value")
tomllib.TOMLDecodeError: Invalid hex value (at line 18, column 18)
```

**Comment by ninjadudexp** [comment]
pulled the new image, no logs were showing went into the container and tryied to run it manually.

```root@28904b8fd8b5:/app# python fanficdownload.py
2024-07-17 12:38:16 AM - Calibre library location not set in the config file.
Traceback (most recent call last):
  File "/app/fanficdownload.py", line 185, in <module>
    main()
  File "/app/fanficdownload.py", line 160, in main
    cdb_info = calibre_info.CalibreInfo(args.config, manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/calibre_info.py", line 38, in __init__
    raise ValueError(message)  # Raise an exception if the path is not set
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Calibre library location not set in the config file.```

**Comment by MrTyton** [comment]
Logs don't appear until it does something. 

Make sure that the app password for the email doesn't have anything that would need to be escaped when parsed by Python or anything else like that. IIRC this includes things like % needing to be doubled up.

**Comment by ninjadudexp** [comment]
> Logs don't appear until it does something.
> 
> Make sure that the app password for the email doesn't have anything that would need to be escaped when parsed by Python or anything else like that. IIRC this includes things like % needing to be doubled up.

did not change anything at all from when it was working, but the password is all letters, from googles app password manager

**Comment by ninjadudexp** [comment]
i went a generated a new code incase that is the issue for whatever reason, and it was.
Will get you log if fails shortly

**Comment by ninjadudexp** [comment]
Got it working, besides the url having to be exactly  url.com/#Calibre_Library, But also i had to make a username and pass and enable login. it is now correctly working

**Comment by MrTyton** [comment]
I will add documentation to help state these requirements. Sorry for the hassle.

**Comment by ninjadudexp** [comment]
No i am appreciative of the time you spent working this out with me,

By default what is the updating mode? ( and how if possible can i change it)

**Comment by MrTyton** [comment]
https://github.com/MrTyton/AutomatedFanfic/blob/master/root/app/url_worker.py#L219

What do you want to change?

**Comment by ninjadudexp** [comment]
Would I just change it to -update-epub? I think forced mode deletes and
readds. And what I want is for it to just add new chapters. This way if
some get deleted in the future I still have it.

**Comment by MrTyton** [comment]
I'll add a config option to disable the forceable options over the next few days. Can you just make an issue for it?
